Proxy helper

diff --git a/shell/bash/functions b/shell/bash/functions
--- a/shell/bash/functions
+++ b/shell/bash/functions
@@ -206,3 +206,70 @@ function docker-copy-image-from-ssh-remote {
         ssh "${SSH_OPTIONS[@]}" 'docker save' "$IMAGE" '| bzip2' | bunzip2 | docker load
     fi
 }
+
+
+## Proxy functions
+## Modified from https://wiki.archlinux.org/index.php/proxy_settings
+function proxy_on() {
+    export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
+    PROXY_CONF=${XDG_CONFIG_HOME:-~/.config}/proxy.config
+
+    if (( $# > 0 )); then
+    # Remove colon since dot after 4th group captures the colon
+        valid=$(prinf "$@" | sed -n 's/\([0-9]\{1,3\}.\)\{4\}\([0-9]\+\)/&/p')
+        if [ "$valid" != "$*" ]; then
+            >&2 printf "Invalid address"
+            return 1
+        fi
+
+        export http_proxy="http://$1"
+        export https_proxy=$http_proxy
+        export ftp_proxy=$http_proxy
+        export rsync_proxy=$http_proxy
+        printf "%s" "Proxy environment variable set to ${http_proxy}"
+        return 0
+    fi
+    if [ -f "$PROXY_CONF" ]; then
+        DEFAULT_PORT=$(awk -F '[:@]' '{ print $(NF)}' "$PROXY_CONF")
+        DEFAULT_HOST=$(awk -F '[:@]' '{ print $(NF-1)}' "$PROXY_CONF")
+    fi
+
+    read -er -p $'Enter Your Proxy Server Username:\n' username
+    if [ -n "$username" ]; then
+        read -er -p $'Enter Your Proxy Server Password:\n' password
+        local pre="$username:$password@"
+    fi
+
+    read -er -p $'Enter Your Proxy Server IP(eg. 192.168.1.110):\n' -i "$DEFAULT_HOST" host
+    read -er -p $'Enter Your Proxy Server Port(eg. 1080):\n' -i "$DEFAULT_PORT" port
+    host=${host:-$DEFAULT_HOST}
+    port=${port:-$DEFAULT_PORT}
+
+    _proxy_addr="http://$pre$host:$port"
+
+    PROXY_ENV="http_proxy ftp_proxy https_proxy all_proxy HTTP_PROXY HTTPS_PROXY FTP_PROXY ALL_PROXY"
+    for envar in $PROXY_ENV
+    do
+        printf "Setting $envar to $_proxy_addr\n"
+        export "$envar"="$_proxy_addr"
+    done
+    printf %s "$host:$port" > "$PROXY_CONF"
+}
+
+function proxy_off(){
+    PROXY_ENV="http_proxy ftp_proxy https_proxy all_proxy no_proxy HTTP_PROXY HTTPS_PROXY FTP_PROXY ALL_PROXY NO_PROXY"
+    for envar in $PROXY_ENV
+    do
+        printf "Unsetting $envar\n"
+        unset "$envar"
+    done
+}
+
+function proxy_status(){
+    PROXY_ENV="http_proxy ftp_proxy https_proxy all_proxy no_proxy HTTP_PROXY HTTPS_PROXY FTP_PROXY ALL_PROXY NO_PROXY"
+    printf "Proxy Status:"
+    for envar in $PROXY_ENV
+    do
+        printf "%s\n" "$envar"="$_proxy_addr"
+    done
+}
